/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        int len = s.size();
        char ret = 0;
        for (int i = 0; i < len; ++i)
            ret ^= s[i] ^ t[i];
        ret ^= t.back();
        return ret;
    }
};

class Solution {
public:
    char findTheDifference(string s, string t) {
        int ascii[128] = {0};
        int lenS = s.size();
        
        int lenT = t.size();
        for (int i = 0; i < lenT; ++i) {
            ++ascii[t[i]];
        }
        for (int i = 0; i < lenS; ++i) {
            --ascii[s[i]];
        }
        for (int i = 0; i < 128; ++i) {
            if (ascii[i])
                return i;
        }
    }
}